### ISSUE TITLE
code_to_compile() generates bad code with FHIR R4 JSON Schema

### ISSUE THREAD

**Issue by gitpushdashf** [horejsek/python-fastjsonschema#109]
`compile()`, however, is fine. Valdiation works as expected. `code_to_compile()` output can be imported, but fails.

```
>>> code.validate_http___hl7_org_fhir_json_schema_4_0(patient)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "code.py", line 86, in validate_http___hl7_org_fhir_json_schema_4_0
    validate_http___hl7_org_fhir_json_schema_4_0__definitions_bundle(data)
  File "code.py", line 67997, in validate_http___hl7_org_fhir_json_schema_4_0__definitions_bundle
    validate_http___hl7_org_fhir_json_schema_4_0__definitions_bundle_entry(data__entry_item)
  File "code.py", line 68055, in validate_http___hl7_org_fhir_json_schema_4_0__definitions_bundle_entry
    validate_http___hl7_org_fhir_json_schema_4_0__definitions_resourcelist(data__resource)
  File "code.py", line 4463, in validate_http___hl7_org_fhir_json_schema_4_0__definitions_resourcelist
    validate_http___hl7_org_fhir_json_schema_4_0__definitions_patient(data)
  File "code.py", line 27084, in validate_http___hl7_org_fhir_json_schema_4_0__definitions_patient
    validate_http___hl7_org_fhir_json_schema_4_0__definitions_extension(data__extension_item)
  File "code.py", line 1688, in validate_http___hl7_org_fhir_json_schema_4_0__definitions_extension
    if not REGEX_PATTERNS['^[ \\r\\n\\t\\S]+$'].search(data__valueString):
KeyError: '^[ \\r\\n\\t\\S]+$'
```

Trying to validate: [85e52038-4d69-50e9-9e46-e379b8d830af.json.txt](https://github.com/horejsek/python-fastjsonschema/files/5736662/85e52038-4d69-50e9-9e46-e379b8d830af.json.txt)
JSON Schema: [fhir.schema.json.txt](https://github.com/horejsek/python-fastjsonschema/files/5736657/fhir.schema.json.txt)

(Had to rename to .txt to upload.)

The JSON Schema is from: http://www.hl7.org/fhir/index.html
The 85e52038-4d69-50e9-9e46-e379b8d830af.json file is a Synthea generated "patient": https://github.com/synthetichealth/synthea

Thank you!

**Comment by gitpushdashf** [comment]
Also, if I call `.compile()` and then try python-jsonschema, fastjsonschema seems to break python-jsonschema.
