### ISSUE TITLE
"date-time" not full supported

### ISSUE THREAD

**Issue by jedie** [horejsek/python-fastjsonschema#115]
e.g.:

```python
>>> import fastjsonschema
>>> fastjsonschema.validate({'type': 'string', 'format': 'date-time'},'2020-09-09T01:01:01+0100')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jens/repos/python-fastjsonschema/fastjsonschema/__init__.py", line 113, in validate
    return compile(definition, handlers, formats, use_default)(data)
  File "<string>", line 8, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data must be date-time
```
Support was added with: https://github.com/horejsek/python-fastjsonschema/pull/7/
But a later refactor seems to remove this.
And there is no test for it: https://github.com/horejsek/python-fastjsonschema/blob/32476cfd4d97f92cae52d686eb471361503bf4ba/tests/test_format.py#L9-L19

**Comment by mars-lan** [comment]
@horejsek could you release a new version to include this fix?

**Comment by horejsek** [comment]
Ah, sorry! Done.

**Comment by tommyjcarpenter** [comment]
hmmm I just hit this issue today using this; `openapi` (formerly known as swagger) uses `datetime`

```
        Valid value for this definition is user@example.com but not @username
        """
        with self.l('if isinstance({variable}, str):'):
            format_ = self._definition['format']
            # Checking custom formats - user is allowed to override default formats.
            if format_ in self._custom_formats:
                custom_format = self._custom_formats[format_]
                if isinstance(custom_format, str):
                    self._generate_format(format_, format_ + '_re_pattern', custom_format)
                else:
                    with self.l('if not custom_formats["{}"]({variable}):', format_):
                        self.exc('{name} must be {}', format_, rule='format')
            elif format_ in self.FORMAT_REGEXS:
                format_regex = self.FORMAT_REGEXS[format_]
                self._generate_format(format_, format_ + '_re_pattern', format_regex)
            # Format regex is used only in meta schemas.
            elif format_ == 'regex':
                with self.l('try:', optimize=False):
                    self.l('re.compile({variable})')
                with self.l('except Exception:'):
                    self.exc('{name} must be a valid regex', rule='format')
            else:
>               raise JsonSchemaDefinitionException('Unknown format: {}'.format(format_))
E               fastjsonschema.exceptions.JsonSchemaDefinitionException: Unknown format: datetime
```
