### ISSUE TITLE
Uniqueness enforced if uniqueItems explicitly set to False

### ISSUE THREAD

**Issue by thormick** [horejsek/python-fastjsonschema#153]
fastjsonschema always enables the uniqueness constraint if a `"uniqueItems"` key is present in the schema, regardless of whether it's value is `True` or `False`.

No urgency for a fix, I'll just delete `uniqueItems` in my project for now.

Test:
```
import jsonschema
import fastjsonschema

json_schema = {
    "type": "array",
    "uniqueItems": False,
    "items": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "id": {"type": "integer"}
        }
    }
}

print(f'fastjsonschema version: {fastjsonschema.VERSION}')

conf = [{'id': 1}, {'id': 1}]
jsonschema.validate(conf, json_schema)
print('jsonschema OK')
fastjsonschema.validate(json_schema, conf)
print('fastjsonschema OK')
```

Expected output:
```
fastjsonschema version: 2.15.3
jsonschema OK
fastjsonschema OK
```
(This is the output if the line `    "uniqueItems": False,` is deleted from the schema.)

Actual output:
```
fastjsonschema version: 2.15.3
jsonschema OK
Traceback (most recent call last):
  File "<string>", line 17, in __PYTHON_EL_eval
  File "/home/thormick/gapit/scratchpad/test_fastjson.py", line 21, in <module>
    fastjsonschema.validate(json_schema, conf)
  File "/home/thormick/gapit/venv-3.9-u20.04/lib/python3.9/site-packages/fastjsonschema/__init__.py", line 114, in validate
    return compile(definition, handlers, formats, use_default)(data)
  File "<string>", line 11, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data must contain unique items
```

If `"uniqueItems": True,` is used instead then `jsonschema.validate` fails as expected.

**Comment by horejsek** [comment]
Thanks for the report! I fixed it and released in version v2.16.1.
