### ISSUE TITLE
Getting UnboundLocalError

### ISSUE THREAD

**Issue by jinsoo960** [horejsek/python-fastjsonschema#157]
Hello,

I am getting a weird error when trying to run validate.
```
data = ["str"]
schema = {"minItems":1, "minLength": 1}
fastjsonschema.validate(schema, data)
```
gives 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../fastjsonschema/__init__.py", line 114, in validate
    return compile(definition, handlers, formats, use_default)(data)
  File "<string>", line 10, in validate
UnboundLocalError: local variable 'data_len' referenced before assignment
```
It seems like something goes wrong when using `minItems`/`maxItems` with `minLength`/`maxLength`?

**Comment by melroy-tellis** [comment]
Arrays can be validated with minItems/maxItems while Strings can be validated with minLength/maxLength as per the JSON Schema specification. There should be an implicit type check (Array for minItems/maxItems, String for minLength/maxLength) along with the length validation. Using minItems along with minLength is arguably an illegal operation since they validate different object types.

https://json-schema.org/draft/2020-12/json-schema-validation.html#name-minlength
https://json-schema.org/draft/2020-12/json-schema-validation.html#name-maxlength
https://json-schema.org/draft/2020-12/json-schema-validation.html#name-maxitems
https://json-schema.org/draft/2020-12/json-schema-validation.html#name-minitems

**Comment by melroy-tellis** [comment]
@horejsek - I have raised a PR for this.
