### ISSUE TITLE
Python 3.10 venv build is failing

### ISSUE THREAD

**Issue by maciejstromich** [horejsek/python-fastjsonschema#161]
While trying to set up `venv` using `make venv` command the process fails with

```
root@f33301812ce6:/# make venv
make: *** No rule to make target 'venv'.  Stop.
root@f33301812ce6:/# cd /app
root@f33301812ce6:/app# make venv
make: Nothing to be done for 'venv'.
root@f33301812ce6:/app# rm -rf venv
root@f33301812ce6:/app# make venv
test -d venv || virtualenv -p python3 venv
created virtual environment CPython3.10.8.final.0-64 in 1862ms
  creator CPython3Posix(dest=/app/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
# Some problem in latest version of setuptools during extracting translations.
/app/venv/bin/python3 -m pip install -U pip setuptools==39.1.0
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.3.1)
Collecting setuptools==39.1.0
  Downloading setuptools-39.1.0-py2.py3-none-any.whl (566 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.8/566.8 kB 7.5 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.6.3
    Uninstalling setuptools-65.6.3:
      Successfully uninstalled setuptools-65.6.3
Successfully installed setuptools-39.1.0
/app/venv/bin/python3 -m pip install -e .[devel]
Obtaining file:///app
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/app/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 12, in <module>
          import setuptools.version
        File "/app/venv/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/app/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 77, in <module>
          __import__('pkg_resources.extern.packaging.requirements')
        File "/app/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
          from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
        File "/app/venv/lib/python3.10/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
          __import__(extant)
        File "/app/venv/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
          collections.MutableMapping.register(ParseResults)
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make: *** [Makefile:22: venv/bin/activate] Error 1
```
environment:
``` 
root@f33301812ce6:/app# python3 --version
Python 3.10.8
root@f33301812ce6:/app# pip --version
pip 22.3.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
```

it's because in python 3.10 MutableMapping is available via collections.abc.MutableMapping and not collections.MutableMapping as it was happening in the prior versions

**Comment by horejsek** [comment]
The problem is in the setuptools, not in this library. Update the library, and it should work.
