### ISSUE TITLE
unspecified required properties yield unexpected behavior

### ISSUE THREAD

**Issue by thehesiod** [horejsek/python-fastjsonschema#185]
it allows you to specify a required property which you have not defined, and results in an error that the object _must_ contain the property:
```python
>>> fastjsonschema.compile({
...     "type": "object",
...     "properties": {
...         "x": {
...             "type": "number",
...         }
...     },
...     "required": ["x", "z"],
...     "additionalProperties": False,
... })({"x": 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 10, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data must contain ['z'] properties
```
ok..so now we specify, and we get an error that it _must not_ exist.
```python
>>> fastjsonschema.compile({
...     "type": "object",
...     "properties": {
...         "x": {
...             "type": "number",
...         }
...     },
...     "required": ["x", "z"],
...     "additionalProperties": False,
... })({"x": 1, "z": 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 18, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data must not contain {'z'} properties
```

so we have a heisen property ;)

also of note, you can have the same property specified more than once:
```>>> fastjsonschema.compile({
...     "type": "object",
...     "properties": {
...         "x": {
...             "type": "number",
...         }
...     },
...     "required": ["x", "x"],
...     "additionalProperties": False,
... })({"x": 1})
{'x': 1}
```
granted this is ok, however may want to not allow?

**Comment by horejsek** [comment]
Thanks, those are great ideas. I released new version with validation support for those two.
