### ISSUE TITLE
UnboundLocalError: local variable 'data_val_is_dict' referenced before assignment

### ISSUE THREAD

**Issue by hurlenko** [horejsek/python-fastjsonschema#49]
Hi there, thanks for this nice library.
The code I'm using
```python
import json
from fastjsonschema import compile
with open("schema.json") as f:
    validator = compile(json.load(f))
with open("instance.json") as f:
    instance = json.load(f)

validator(instance)
```

raises this exception
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 37, in validate
  File "<string>", line 37, in validate
  File "<string>", line 46, in validate
UnboundLocalError: local variable 'data_val_is_dict' referenced before assignment
```
`schema.json`:
```json
{
  "type": "object",
  "additionalProperties": false,
  "required": [
    "question"
  ],
  "patternProperties": {
    "question": {},
    "predef\\d": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "next",
        "text"
      ],
      "properties": {
        "text": {
          "type": "string"
        },
        "next": {
          "$ref": "#"
        }
      }
    },
    "media\\d": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "content_type",
        "content_path"
      ],
      "properties": {
        "content_type": {
          "type": "string"
        },
        "content_path": {
          "type": "string"
        },
        "next": {
          "$ref": "#"
        }
      }
    }
  }
}
```

`instance.json`: 
```json
{
  "question": "sample text",
  "predef1": {
    "text": "sample text",
    "next": {
      "question": "sample text",
      "predef1": {
        "text": "sample text",
        "next": {
          "question": "sample text"
        }
      },
      "predef2": {
        "text": "sample text",
        "next": {
          "question": "sample text",
          "media1": {
            "content_type": "type",
            "content_path": "url",
            "next": {
              "question": "sample text",
              "predef1": {
                "text": "sample text",
                "next": {
                  "question": "sample text"
                }
              },
              "predef2": {
                "text": "sample text",
                "next": {
                  "question": "sample text",
                  "media1": {
                    "content_type": "type",
                    "content_path": "url"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
I used several online schema validators so I'm pretty sure that both the schema and the instance are correct. I believe it has something to do with `"$ref": "#"` but I didn't have time to find the cause of this exception.

**Comment by horejsek** [comment]
Thanks for the report! Fixed in version v2.12, just uploaded.
