### ISSUE TITLE
UnboundLocalError: local variable 'data_val__contentpath_len' referenced before assignment

### ISSUE THREAD

**Issue by hurlenko** [horejsek/python-fastjsonschema#53]
Hello,
Having this error on the latest version (`fastjsonschema==2.13`). Seems to be related to #49 

[instance.txt](https://github.com/horejsek/python-fastjsonschema/files/3306451/instance.txt)
[schema.txt](https://github.com/horejsek/python-fastjsonschema/files/3306452/schema.txt)

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "fastjsonschema/__init__.py", line 103, in validate
    return compile(definition)(data)
  File "<string>", line 48, in validate
  File "<string>", line 104, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 104, in validate___scenario
  [Previous line repeated 1 more time]
  File "<string>", line 150, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 150, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 104, in validate___scenario
  [Previous line repeated 4 more times]
  File "<string>", line 150, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 150, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 104, in validate___scenario
  File "<string>", line 137, in validate___scenario
UnboundLocalError: local variable 'data_val__contentpath_len' referenced before assignment
```
Sorry for such a big example. That seems to be the smallest example to reproduce this bug.

**Comment by horejsek** [comment]
Thank you for the report. I had not much time in last months to address issues in this library. Will try to do it sometime in following weeks.

**Comment by horejsek** [comment]
Fixed in master, will be released next week.
