### ISSUE TITLE
Compiling json schema gives TypeError: string indices must be integers

### ISSUE THREAD

**Issue by victoraugustofd** [horejsek/python-fastjsonschema#78]
Hi there,

I'm trying to compile my schema with fastjsonschema and it is returning this error:

The trace:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Program Files\Python\lib\site-packages\fastjsonschema\__init__.py", line 164, in compile
>     resolver, code_generator = _factory(definition, handlers, formats)
>   File "C:\Program Files\Python\lib\site-packages\fastjsonschema\__init__.py", line 204, in _factory
>     resolver = RefResolver.from_schema(definition, handlers=handlers)
>   File "C:\Program Files\Python\lib\site-packages\fastjsonschema\ref_resolver.py", line 85, in from_schema
>     return cls(
>   File "C:\Program Files\Python\lib\site-packages\fastjsonschema\ref_resolver.py", line 78, in __init__
>     self.walk(schema)
>   File "C:\Program Files\Python\lib\site-packages\fastjsonschema\ref_resolver.py", line 148, in walk
>     elif '$ref' in node and isinstance(node['$ref'], str):
> TypeError: string indices must be integers

The code:
```
import fastjsonschema

schema_file = open("phoenix-schema.json")
schema_content = schema_file.read()
validation = fastjsonschema.compile(schema_content)
```

The schema:

> {
>     "$id": "https://github.com/victoraugustofd/git-phoenix/blob/master/src/phoenix-schema.json",
>     "$schema": "http://json-schema.org/draft-07/schema#",
>     "title": "Git Phoenix Template Schema",
>     "description": "A schema validator for Git Phoenix templates.",
>     "definitions": {
>         "actions": {
>             "$id": "#actions",
>             "type": "string",
>             "enum": [
>                 "create-branch",
>                 "merge"
>             ]
>         },
>         "execution": {
>             "$id": "#execution",
>             "type": "object",
>             "properties": {
>                 "step": {
>                     "type": "integer"
>                 },
>                 "do": {
>                     "type": "object",
>                     "properties": {
>                         "action": {
>                             "$ref": "#actions"
>                         },
>                         "parameters": {
>                             "type": "object"
>                         }
>                     },
>                     "allOf": [
>                         {
>                             "if": {
>                                 "properties": {
>                                     "action": {
>                                         "const": "create-branch"
>                                     }
>                                 }
>                             },
>                             "then": {
>                                 "properties": {
>                                     "parameters": {
>                                         "properties": {
>                                             "name": {
>                                                 "type": "string"
>                                             },
>                                             "origin": {
>                                                 "type": "string"
>                                             },
>                                             "origin-pattern": {
>                                                 "type": "string"
>                                             },
>                                             "origin-pattern-example": {
>                                                 "type": "string"
>                                             },
>                                             "prefix": {
>                                                 "type": "string"
>                                             },
>                                             "pattern": {
>                                                 "type": "string"
>                                             },
>                                             "pattern-example": {
>                                                 "type": "string"
>                                             }
>                                         },
>                                         "required": [
>                                             "name",
>                                             "origin"
>                                         ],
>                                         "additionalProperties": false
>                                     }
>                                 }
>                             }
>                         },
>                         {
>                             "if": {
>                                 "properties": {
>                                     "action": {
>                                         "const": "merge"
>                                     }
>                                 }
>                             },
>                             "then": {
>                                 "properties": {
>                                     "parameters": {
>                                         "properties": {
>                                             "origin": {
>                                                 "type": "string"
>                                             },
>                                             "destination": {
>                                                 "type": "array",
>                                                 "items": {
>                                                     "type": "string"
>                                                 },
>                                                 "minItems": 1
>                                             },
>                                             "origin-pattern": {
>                                                 "type": "string"
>                                             },
>                                             "origin-pattern-example": {
>                                                 "type": "string"
>                                             },
>                                             "allow-new-merge": {
>                                                 "type": "boolean"
>                                             }
>                                         },
>                                         "required": [
>                                             "origin",
>                                             "destination"
>                                         ],
>                                         "additionalProperties": false
>                                     }
>                                 }
>                             }
>                         }
>                     ],
>                     "required": [
>                         "action",
>                         "parameters"
>                     ],
>                     "additionalProperties": false
>                 }
>             },
>             "required": [
>                 "step",
>                 "do"
>             ],
>             "additionalProperties": false
>         },
>         "action": {
>             "$id": "#action",
>             "type": "object",
>             "properties": {
>                 "name": {
>                     "type": "string"
>                 },
>                 "execution": {
>                     "type": "array",
>                     "items": {
>                         "$ref": "#execution"
>                     },
>                     "minItems": 1
>                 }
>             },
>             "required": [
>                 "name",
>                 "execution"
>             ],
>             "additionalProperties": false
>         },
>         "command": {
>             "$id": "#command",
>             "type": "object",
>             "properties": {
>                 "name": {
>                     "type": "string"
>                 },
>                 "actions": {
>                     "type": "array",
>                     "items": {
>                         "$ref": "#action"
>                     },
>                     "minItems": 1
>                 }
>             },
>             "required": [
>                 "name",
>                 "actions"
>             ],
>             "additionalProperties": false
>         }
>     },
>     "type": "object",
>     "properties": {
>         "init": {
>             "type": "object",
>             "properties": {
>                 "execution": {
>                     "type": "array",
>                     "items": {
>                         "$ref": "#execution"
>                     },
>                     "minItems": 1
>                 }
>             }
>         },
>         "commons": {
>             "type": "object"
>         },
>         "commands": {
>             "type": "array",
>             "items": {
>                 "$ref": "#command"
>             },
>             "minItems": 1
>         }
>     },
>     "required": [
>         "commands"
>     ],
>     "additionalProperties": false
> }

This problem was already discussed on issue #59, but I didn't find the solution there.

Could you help me, please?
Thanks in advance.

**Comment by victoraugustofd** [comment]
For those who face the same problem, here is the solution:
Reading the JSON Schema returns a String and not a dictionary, which is what the method **walk** expect as its parameter.
The error returned is not clear about that, and I was looking for a solution without even imagining that it was a str and not a dict.
For the method _compile_ work, you should execute it passing a dict, and I did that with the following code:
`import fastjsonschema
import json

schema_file = open("phoenix-schema.json")
schema_content_str = schema_file.read()
schema_content_dict = json.loads(schema_content_str)
validation = fastjsonschema.compile(schema_content_dict)`

After that, I faced an error regarding inner references from "definitions" scope on a JSON Schema.
Even I indexing my definitions with a "#", the compile didn't work.
So I added the full reference, like this: 
`"items": {
    "$ref": "#/definitions/command"
}`
, for example.

@horejsek, it would be interesting to add these infos on the documentation.
Thanks.
